# Generated by Django 2.0.2 on 2018-02-24 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20180224_1237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='onDuty',
            new_name='on_duty',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
