# Generated by Django 2.0.2 on 2018-02-10 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Grade')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.ClassRoom')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Teacher')),
            ],
        ),
        migrations.AlterField(
            model_name='lessontime',
            name='end',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='lessontime',
            name='start',
            field=models.TimeField(),
        ),
        migrations.AddField(
            model_name='shedule',
            name='time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.LessonTime'),
        ),
    ]
