# Generated by Django 2.0.2 on 2018-02-10 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20180210_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessontime',
            name='number',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
