# Generated by Django 2.0.2 on 2018-02-10 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_lessontime_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='SheduleItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], max_length=1)),
                ('even_odd', models.CharField(choices=[(0, None), (1, 'Even'), (2, 'Odd')], default=0, max_length=1)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Grade')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.ClassRoom')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Teacher')),
            ],
        ),
        migrations.RemoveField(
            model_name='shedule',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='shedule',
            name='room',
        ),
        migrations.RemoveField(
            model_name='shedule',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='shedule',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='shedule',
            name='time',
        ),
        migrations.AlterField(
            model_name='lessontime',
            name='number',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.DeleteModel(
            name='Shedule',
        ),
        migrations.AddField(
            model_name='sheduleitem',
            name='time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.LessonTime'),
        ),
    ]
