# Generated by Django 2.0.2 on 2018-02-13 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_auto_20180210_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheduleitem',
            name='day',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=0),
        ),
        migrations.AlterField(
            model_name='sheduleitem',
            name='even_odd',
            field=models.CharField(blank=True, choices=[('even', 'Even'), ('odd', 'Odd')], max_length=1),
        ),
    ]
